[versions]
kotlinx-serialization = "1.3.0"
lkws = "1.2"
pretty-log = "1.4"
bindables = "1.1"
hollow = "1.0"

[libraries]
hollow = {group = "cz.lukynka", name = "hollow", version.ref = "hollow"}
kotlinx-core = {group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization"}
kotlinx-json = {group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization"}
lkws = {group = "cz.lukynka", name = "lkws", version.ref = "lkws"}
pretty-log = {group = "cz.lukynka", name = "pretty-log", version.ref = "pretty-log"}
bindables = {group = "cz.lukynka", name = "kotlin-bindables", version.ref = "bindables"}

[bundles]
kotlinx = ["kotlinx-core", "kotlinx-json"]
lkws = ["lkws", "pretty-log"]
